# Generated by Django 4.1.7 on 2023-03-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scbapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
